# Generated by Django 5.1.2 on 2024-11-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="proDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "ProductName",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("Price", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "ProductDescription",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("Quantity", models.IntegerField(blank=True, null=True)),
                (
                    "ProductImage",
                    models.ImageField(
                        blank=True, null=True, upload_to="Category Images"
                    ),
                ),
            ],
        ),
    ]
