# Generated by Django 5.1.2 on 2024-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customersDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CustomerName",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "CustomerEmail",
                    models.EmailField(blank=True, max_length=200, null=True),
                ),
                (
                    "CustomerPlace",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "CustomerSubject",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "CustomerMessage",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
    ]
